# Generated by Django 6.0.4 on 2026-04-30 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_log_review_timesheet_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='log_id',
            field=models.IntegerField(),
        ),
    ]
